server:
  port: 8080

spring:
  application:
    name: service-a

service:
  b:
    url: ${SERVICE_B_URL:http://service-b:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.example.otel: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
