apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
      - name: victoriametrics
        image: victoriametrics/victoria-metrics:v1.93.5
        args:
          - -storageDataPath=/storage
          - -retentionPeriod=14d
          - -httpListenAddr=:8428
        ports:
        - containerPort: 8428
          name: http
        volumeMounts:
        - name: storage
          mountPath: /storage
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: victoriametrics-storage
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: monitoring
  labels:
    app: victoriametrics
spec:
  type: LoadBalancer
  ports:
  - port: 8428
    targetPort: 8428
    name: http
  selector:
    app: victoriametrics
