server:
  port: 8082

spring:
  application:
    name: service-c
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres.services.svc.cluster.local}:${DB_PORT:5432}/${DB_NAME:demo_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Abcd}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.example.otel: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
