apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
    component: agent
spec:
  selector:
    matchLabels:
      app: jaeger
      component: agent
  template:
    metadata:
      labels:
        app: jaeger
        component: agent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14271"
        prometheus.io/path: "/metrics"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: jaeger-agent
        image: jaegertracing/jaeger-agent:1.50
        args:
        - --reporter.grpc.host-port=jaeger-collector.monitoring.svc.cluster.local:14250
        - --reporter.type=grpc
        - --agent.tags=cluster=monitoring-demo,deployment.environment=production

        ports:
        - containerPort: 5775
          protocol: UDP
          name: zipkin-compact
        - containerPort: 6831
          protocol: UDP
          name: jaeger-compact
        - containerPort: 6832
          protocol: UDP
          name: jaeger-binary
        - containerPort: 5778
          protocol: TCP
          name: configs
        - containerPort: 14271
          protocol: TCP
          name: admin

        livenessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 10
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 14271
          initialDelaySeconds: 5
          periodSeconds: 5

        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5775
    protocol: UDP
    name: zipkin-compact
  - port: 6831
    protocol: UDP
    name: jaeger-compact
  - port: 6832
    protocol: UDP
    name: jaeger-binary
  - port: 5778
    protocol: TCP
    name: configs
  - port: 14271
    protocol: TCP
    name: admin
  selector:
    app: jaeger
    component: agent
