apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "14269"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.50
        env:
        # Storage configuration
        - name: SPAN_STORAGE_TYPE
          value: "badger"
        - name: BADGER_EPHEMERAL
          value: "false"
        - name: BADGER_DIRECTORY_VALUE
          value: "/badger/data"
        - name: BADGER_DIRECTORY_KEY
          value: "/badger/key"
        - name: BADGER_SPAN_STORE_TTL
          value: "168h"  # 7 days

        # Collector configuration
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"

        # Service Performance Monitoring (SPM)
        - name: METRICS_STORAGE_TYPE
          value: "prometheus"
        - name: PROMETHEUS_SERVER_URL
          value: "http://prometheus.monitoring.svc.cluster.local:9090"
        - name: PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR
          value: "true"
        - name: PROMETHEUS_QUERY_NORMALIZE_CALLS
          value: "true"
        - name: PROMETHEUS_QUERY_NORMALIZE_DURATION
          value: "true"

        # Sampling configuration
        - name: SAMPLING_STRATEGIES_FILE
          value: "/etc/jaeger/sampling.json"

        # Query configuration
        - name: QUERY_BASE_PATH
          value: "/"

        ports:
        # Jaeger UI
        - containerPort: 16686
          name: ui
          protocol: TCP
        # Collector gRPC
        - containerPort: 14250
          name: grpc
          protocol: TCP
        # Collector HTTP
        - containerPort: 14268
          name: http
          protocol: TCP
        # OTLP gRPC
        - containerPort: 4317
          name: otlp-grpc
          protocol: TCP
        # OTLP HTTP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        # Zipkin
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        # Admin/Metrics
        - containerPort: 14269
          name: admin
          protocol: TCP

        volumeMounts:
        - name: badger-storage
          mountPath: /badger
        - name: sampling-config
          mountPath: /etc/jaeger

        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 5

        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

      volumes:
      - name: badger-storage
        persistentVolumeClaim:
          claimName: jaeger-storage
      - name: sampling-config
        configMap:
          name: jaeger-sampling-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: NodePort
  ports:
  - port: 16686
    targetPort: 16686
    nodePort: 30002
    name: ui
  - port: 16687
    targetPort: 14269
    name: admin
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    app: jaeger
spec:
  type: ClusterIP
  ports:
  - port: 14250
    targetPort: 14250
    name: grpc
  - port: 14268
    targetPort: 14268
    name: http
  - port: 4317
    targetPort: 4317
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    name: otlp-http
  - port: 9411
    targetPort: 9411
    name: zipkin
  - port: 14269
    targetPort: 14269
    name: admin
  selector:
    app: jaeger
