---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: monitoring
  labels:
    app: kiali
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
rules:
# Kiali needs to read Kubernetes resources to build the service graph
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
  - namespaces
  - nodes
  - pods
  - pods/log
  - replicationcontrollers
  - services
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - pods/portforward
  verbs: ["create", "post"]
- apiGroups: ["extensions", "apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps.openshift.io"]
  resources:
  - deploymentconfigs
  verbs: ["get", "list", "watch"]
- apiGroups: ["project.openshift.io"]
  resources:
  - projects
  verbs: ["get"]
- apiGroups: ["route.openshift.io"]
  resources:
  - routes
  verbs: ["get"]
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
# Kiali needs to read Istio resources if using service mesh
- apiGroups: ["networking.istio.io"]
  resources:
  - destinationrules
  - gateways
  - serviceentries
  - sidecars
  - virtualservices
  - workloadentries
  - workloadgroups
  verbs: ["get", "list", "watch"]
- apiGroups: ["security.istio.io"]
  resources:
  - authorizationpolicies
  - peerauthentications
  - requestauthentications
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali
  labels:
    app: kiali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
- kind: ServiceAccount
  name: kiali
  namespace: monitoring
