---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
rules:
  # Kiali needs to read and manage Kubernetes resources
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - pods
      - pods/log
      - replicationcontrollers
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - nodes
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods/portforward
    verbs: ["create", "post"]
  - apiGroups: ["extensions", "apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps.openshift.io"]
    resources:
      - deploymentconfigs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs: ["get"]
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs: ["get"]
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs: ["create"]
  # Kiali needs full permissions to manage Istio resources
  - apiGroups: ["networking.istio.io"]
    resources:
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
      - workloadentries
      - workloadgroups
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gateways
      - httproutes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["security.istio.io"]
    resources:
      - authorizationpolicies
      - peerauthentications
      - requestauthentications
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["extensions.istio.io"]
    resources:
      - wasmplugins
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["telemetry.istio.io"]
    resources:
      - telemetries
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali
  labels:
    app: kiali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
  - kind: ServiceAccount
    name: kiali
    namespace: istio-system
