apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: services
  labels:
    app: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9464"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        - containerPort: 9464
          name: metrics
        env:
        - name: SERVICE_C_URL
          value: "http://service-c.services.svc.cluster.local:8082"
        - name: OTEL_SERVICE_NAME
          value: "service-b"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otel-collector.monitoring.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
          value: "grpc"
        - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
          value: "true"
        - name: OTEL_METRICS_EXPORTER
          value: "prometheus"
        - name: OTEL_EXPORTER_PROMETHEUS_HOST
          value: "0.0.0.0"
        - name: OTEL_EXPORTER_PROMETHEUS_PORT
          value: "9464"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 45
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: services
  labels:
    app: service-b
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9464"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: service-b
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: metrics
    port: 9464
    targetPort: 9464
