server:
  port: 8081

spring:
  application:
    name: service-b

service:
  c:
    url: ${SERVICE_C_URL:http://service-c:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.example.otel: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
